# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_hor.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(954, 822)
        MainWindow.setAcceptDrops(True)
        icon = QIcon()
        icon.addFile(u"../../../../../../.designer/backup/main_window.ico", QSize(), QIcon.Normal, QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.actionOpen_TIFFs = QAction(MainWindow)
        self.actionOpen_TIFFs.setObjectName(u"actionOpen_TIFFs")
        self.actionOpen_Zip_TIFFs = QAction(MainWindow)
        self.actionOpen_Zip_TIFFs.setObjectName(u"actionOpen_Zip_TIFFs")
        self.actionOpen_Zip_H5 = QAction(MainWindow)
        self.actionOpen_Zip_H5.setObjectName(u"actionOpen_Zip_H5")
        self.actionProject_TRee = QAction(MainWindow)
        self.actionProject_TRee.setObjectName(u"actionProject_TRee")
        self.actionProject_TRee.setCheckable(True)
        self.actiontest_bar = QAction(MainWindow)
        self.actiontest_bar.setObjectName(u"actiontest_bar")
        self.actionOpen_Folder = QAction(MainWindow)
        self.actionOpen_Folder.setObjectName(u"actionOpen_Folder")
        self.actionOpen_ZIP = QAction(MainWindow)
        self.actionOpen_ZIP.setObjectName(u"actionOpen_ZIP")
        self.actionImage = QAction(MainWindow)
        self.actionImage.setObjectName(u"actionImage")
        self.actionArray = QAction(MainWindow)
        self.actionArray.setObjectName(u"actionArray")
        self.actionDataset = QAction(MainWindow)
        self.actionDataset.setObjectName(u"actionDataset")
        self.actionOpen_NPY = QAction(MainWindow)
        self.actionOpen_NPY.setObjectName(u"actionOpen_NPY")
        self.actionGroup_by_delay = QAction(MainWindow)
        self.actionGroup_by_delay.setObjectName(u"actionGroup_by_delay")
        self.actionROI_avg_intensity = QAction(MainWindow)
        self.actionROI_avg_intensity.setObjectName(u"actionROI_avg_intensity")
        self.actionImport_Dataset = QAction(MainWindow)
        self.actionImport_Dataset.setObjectName(u"actionImport_Dataset")
        self.actionSet_center = QAction(MainWindow)
        self.actionSet_center.setObjectName(u"actionSet_center")
        self.actionCalculate = QAction(MainWindow)
        self.actionCalculate.setObjectName(u"actionCalculate")
        self.actionSubtract_first_image = QAction(MainWindow)
        self.actionSubtract_first_image.setObjectName(u"actionSubtract_first_image")
        self.actionRadial_Average = QAction(MainWindow)
        self.actionRadial_Average.setObjectName(u"actionRadial_Average")
        self.action2x2 = QAction(MainWindow)
        self.action2x2.setObjectName(u"action2x2")
        self.action3x3 = QAction(MainWindow)
        self.action3x3.setObjectName(u"action3x3")
        self.action5x5 = QAction(MainWindow)
        self.action5x5.setObjectName(u"action5x5")
        self.action10x10 = QAction(MainWindow)
        self.action10x10.setObjectName(u"action10x10")
        self.actionSlice_Data = QAction(MainWindow)
        self.actionSlice_Data.setObjectName(u"actionSlice_Data")
        self.actionDownsample_to_16bit = QAction(MainWindow)
        self.actionDownsample_to_16bit.setObjectName(u"actionDownsample_to_16bit")
        self.actionOpen_single_H5_serie = QAction(MainWindow)
        self.actionOpen_single_H5_serie.setObjectName(u"actionOpen_single_H5_serie")
        self.actionSet_000_position = QAction(MainWindow)
        self.actionSet_000_position.setObjectName(u"actionSet_000_position")
        self.actionPattern_simulator = QAction(MainWindow)
        self.actionPattern_simulator.setObjectName(u"actionPattern_simulator")
        self.actionOpen_SPE = QAction(MainWindow)
        self.actionOpen_SPE.setObjectName(u"actionOpen_SPE")
        self.actionPlotter = QAction(MainWindow)
        self.actionPlotter.setObjectName(u"actionPlotter")
        self.actionCalibrate_image = QAction(MainWindow)
        self.actionCalibrate_image.setObjectName(u"actionCalibrate_image")
        self.actionMeasure_distance = QAction(MainWindow)
        self.actionMeasure_distance.setObjectName(u"actionMeasure_distance")
        self.actionMeasure_distance.setCheckable(True)
        self.actionNew_window = QAction(MainWindow)
        self.actionNew_window.setObjectName(u"actionNew_window")
        self.actionAdd_ROI = QAction(MainWindow)
        self.actionAdd_ROI.setObjectName(u"actionAdd_ROI")
        self.actionRemove_ROI = QAction(MainWindow)
        self.actionRemove_ROI.setObjectName(u"actionRemove_ROI")
        self.actionRemove_All = QAction(MainWindow)
        self.actionRemove_All.setObjectName(u"actionRemove_All")
        self.actionSelect_loops = QAction(MainWindow)
        self.actionSelect_loops.setObjectName(u"actionSelect_loops")
        self.actionConsole = QAction(MainWindow)
        self.actionConsole.setObjectName(u"actionConsole")
        self.actionMetadata_Panel = QAction(MainWindow)
        self.actionMetadata_Panel.setObjectName(u"actionMetadata_Panel")
        self.actionMetadata_Panel.setCheckable(True)
        self.actionMetadata_Panel.setChecked(True)
        self.actionLinear = QAction(MainWindow)
        self.actionLinear.setObjectName(u"actionLinear")
        self.actionLinear.setCheckable(True)
        self.actionLog = QAction(MainWindow)
        self.actionLog.setObjectName(u"actionLog")
        self.actionLog.setCheckable(True)
        self.actionArcsinh = QAction(MainWindow)
        self.actionArcsinh.setObjectName(u"actionArcsinh")
        self.actionArcsinh.setCheckable(True)
        self.actionSquare = QAction(MainWindow)
        self.actionSquare.setObjectName(u"actionSquare")
        self.actionSquare.setCheckable(True)
        self.actionNew_window_2 = QAction(MainWindow)
        self.actionNew_window_2.setObjectName(u"actionNew_window_2")
        self.actionDiff_On_Off = QAction(MainWindow)
        self.actionDiff_On_Off.setObjectName(u"actionDiff_On_Off")
        self.actionSwap_On_Off = QAction(MainWindow)
        self.actionSwap_On_Off.setObjectName(u"actionSwap_On_Off")
        self.actionDummy_data = QAction(MainWindow)
        self.actionDummy_data.setObjectName(u"actionDummy_data")
        self.actionShow_On_Off = QAction(MainWindow)
        self.actionShow_On_Off.setObjectName(u"actionShow_On_Off")
        self.actionShow_On = QAction(MainWindow)
        self.actionShow_On.setObjectName(u"actionShow_On")
        self.actionShow_Off = QAction(MainWindow)
        self.actionShow_Off.setObjectName(u"actionShow_Off")
        self.actionGaussian_smooth = QAction(MainWindow)
        self.actionGaussian_smooth.setObjectName(u"actionGaussian_smooth")
        self.actionDataset_ON_OFF = QAction(MainWindow)
        self.actionDataset_ON_OFF.setObjectName(u"actionDataset_ON_OFF")
        self.actionImport_Dataset_ON_OFF = QAction(MainWindow)
        self.actionImport_Dataset_ON_OFF.setObjectName(u"actionImport_Dataset_ON_OFF")
        self.actionGaussian_smooth_ON_OFF = QAction(MainWindow)
        self.actionGaussian_smooth_ON_OFF.setObjectName(u"actionGaussian_smooth_ON_OFF")
        self.actionON_OFF = QAction(MainWindow)
        self.actionON_OFF.setObjectName(u"actionON_OFF")
        self.actionRemove_hot_n_2 = QAction(MainWindow)
        self.actionRemove_hot_n_2.setObjectName(u"actionRemove_hot_n_2")
        self.actionRemove_outliers = QAction(MainWindow)
        self.actionRemove_outliers.setObjectName(u"actionRemove_outliers")
        self.actionRemove_outliers_imgOFF = QAction(MainWindow)
        self.actionRemove_outliers_imgOFF.setObjectName(u"actionRemove_outliers_imgOFF")
        self.action1 = QAction(MainWindow)
        self.action1.setObjectName(u"action1")
        self.action2 = QAction(MainWindow)
        self.action2.setObjectName(u"action2")
        self.action3 = QAction(MainWindow)
        self.action3.setObjectName(u"action3")
        self.action4 = QAction(MainWindow)
        self.action4.setObjectName(u"action4")
        self.action5 = QAction(MainWindow)
        self.action5.setObjectName(u"action5")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_3 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.frame_3)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Plain)
        self.gridLayout_4 = QGridLayout(self.frame_6)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.groupBox_2 = QGroupBox(self.frame_6)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.gridLayout_6 = QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_6.addItem(self.verticalSpacer_3, 2, 0, 1, 1)

        self.frame = QFrame(self.groupBox_2)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.frame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.fit_G = QRadioButton(self.frame)
        self.fit_G.setObjectName(u"fit_G")
        self.fit_G.setChecked(True)

        self.horizontalLayout_6.addWidget(self.fit_G)

        self.fit_V = QRadioButton(self.frame)
        self.fit_V.setObjectName(u"fit_V")

        self.horizontalLayout_6.addWidget(self.fit_V)


        self.gridLayout_6.addWidget(self.frame, 0, 1, 1, 1)

        self.fit_voigt_btn = QPushButton(self.groupBox_2)
        self.fit_voigt_btn.setObjectName(u"fit_voigt_btn")

        self.gridLayout_6.addWidget(self.fit_voigt_btn, 1, 1, 1, 1)

        self.fit_gauss_btn = QPushButton(self.groupBox_2)
        self.fit_gauss_btn.setObjectName(u"fit_gauss_btn")

        self.gridLayout_6.addWidget(self.fit_gauss_btn, 1, 0, 1, 1)

        self.fit_chkbx = QCheckBox(self.groupBox_2)
        self.fit_chkbx.setObjectName(u"fit_chkbx")

        self.gridLayout_6.addWidget(self.fit_chkbx, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.frame_6)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.gridLayout_5 = QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.pushButton_2 = QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.gridLayout_5.addWidget(self.pushButton_2, 1, 0, 1, 1)

        self.pushButton_4 = QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.gridLayout_5.addWidget(self.pushButton_4, 2, 0, 1, 1)

        self.pushButton_3 = QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.gridLayout_5.addWidget(self.pushButton_3, 1, 1, 1, 1)

        self.pushButton = QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(u"pushButton")

        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_5.addItem(self.verticalSpacer, 5, 0, 1, 1)

        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout_5.addWidget(self.label_2, 3, 0, 1, 2)

        self.checkBox_3 = QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName(u"checkBox_3")

        self.gridLayout_5.addWidget(self.checkBox_3, 4, 0, 1, 1)

        self.checkBox_2 = QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName(u"checkBox_2")

        self.gridLayout_5.addWidget(self.checkBox_2, 2, 1, 1, 1)

        self.roi_chkbx = QCheckBox(self.groupBox_3)
        self.roi_chkbx.setObjectName(u"roi_chkbx")

        self.gridLayout_5.addWidget(self.roi_chkbx, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.groupBox_6 = QGroupBox(self.frame_6)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.gridLayout_11 = QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.label = QLabel(self.groupBox_6)
        self.label.setObjectName(u"label")

        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox_6, 3, 0, 1, 1)

        self.groupBox = QGroupBox(self.frame_6)
        self.groupBox.setObjectName(u"groupBox")
        self.gridLayout_7 = QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-180.000000000000000)
        self.doubleSpinBox.setMaximum(180.000000000000000)

        self.gridLayout_7.addWidget(self.doubleSpinBox, 4, 1, 1, 3)

        self.checkBox_pump = QCheckBox(self.groupBox)
        self.checkBox_pump.setObjectName(u"checkBox_pump")
        self.checkBox_pump.setEnabled(True)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_pump.setFont(font)
        self.checkBox_pump.setAutoFillBackground(False)
        self.checkBox_pump.setChecked(True)

        self.gridLayout_7.addWidget(self.checkBox_pump, 8, 0, 1, 1)

        self.spinBox_2 = QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setEnabled(True)
        self.spinBox_2.setMaximum(990000)
        self.spinBox_2.setValue(1)

        self.gridLayout_7.addWidget(self.spinBox_2, 3, 3, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_7.addItem(self.verticalSpacer_2, 5, 0, 1, 1)

        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.gridLayout_7.addWidget(self.pushButton_5, 4, 0, 1, 1)

        self.sum_chkbx = QCheckBox(self.groupBox)
        self.sum_chkbx.setObjectName(u"sum_chkbx")

        self.gridLayout_7.addWidget(self.sum_chkbx, 2, 0, 1, 1)

        self.comboBox_3 = QComboBox(self.groupBox)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")

        self.gridLayout_7.addWidget(self.comboBox_3, 0, 1, 1, 3)

        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")

        self.gridLayout_7.addWidget(self.checkBox, 3, 0, 1, 1)

        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout_7.addWidget(self.label_4, 3, 2, 1, 1)

        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)

        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setEnabled(True)
        self.spinBox.setMaximum(990000)
        self.spinBox.setSingleStep(1)

        self.gridLayout_7.addWidget(self.spinBox, 3, 1, 1, 1)

        self.export_img_btn = QPushButton(self.groupBox)
        self.export_img_btn.setObjectName(u"export_img_btn")

        self.gridLayout_7.addWidget(self.export_img_btn, 1, 0, 1, 1)

        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout_7.addWidget(self.label_7, 7, 0, 1, 2)

        self.shift_0order_btn = QPushButton(self.groupBox)
        self.shift_0order_btn.setObjectName(u"shift_0order_btn")

        self.gridLayout_7.addWidget(self.shift_0order_btn, 6, 0, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)

        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)

        self.gridLayout.addWidget(self.frame_6, 0, 0, 2, 1)

        self.tabWidget = QTabWidget(self.frame_2)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_3 = QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.widget_4 = PlotWidget(self.tab)
        self.widget_4.setObjectName(u"widget_4")

        self.verticalLayout_3.addWidget(self.widget_4)

        self.widget_5 = PlotWidget(self.tab)
        self.widget_5.setObjectName(u"widget_5")

        self.verticalLayout_3.addWidget(self.widget_5)

        self.widget_6 = PlotWidget(self.tab)
        self.widget_6.setObjectName(u"widget_6")

        self.verticalLayout_3.addWidget(self.widget_6)

        self.frame_4 = QFrame(self.tab)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy2)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.gridLayout_12 = QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.comboBox_2 = QComboBox(self.frame_4)
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.gridLayout_12.addWidget(self.comboBox_2, 1, 1, 1, 1)

        self.comboBox = QComboBox(self.frame_4)
        self.comboBox.setObjectName(u"comboBox")

        self.gridLayout_12.addWidget(self.comboBox, 1, 0, 1, 1)

        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy3)
        self.label_9.setAlignment(Qt.AlignCenter)

        self.gridLayout_12.addWidget(self.label_9, 0, 0, 1, 1)

        self.label_10 = QLabel(self.frame_4)
        self.label_10.setObjectName(u"label_10")
        sizePolicy3.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy3)
        self.label_10.setAlignment(Qt.AlignCenter)

        self.gridLayout_12.addWidget(self.label_10, 0, 1, 1, 1)


        self.verticalLayout_3.addWidget(self.frame_4)

        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout_4 = QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.tableView_2 = QTableView(self.tab_2)
        self.tableView_2.setObjectName(u"tableView_2")
        self.tableView_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableView_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableView_2.horizontalHeader().setDefaultSectionSize(150)
        self.tableView_2.horizontalHeader().setStretchLastSection(True)

        self.verticalLayout_4.addWidget(self.tableView_2)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.horizontalLayout_7 = QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.notes_lbl = QLabel(self.tab_3)
        self.notes_lbl.setObjectName(u"notes_lbl")
        self.notes_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.horizontalLayout_7.addWidget(self.notes_lbl)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.gridLayout_3 = QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tableView = QTableView(self.tab_4)
        self.tableView.setObjectName(u"tableView")

        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_4, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 3, 2, 1)

        self.frame_5 = QFrame(self.frame_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.gridLayout_13 = QGridLayout(self.frame_5)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.frame1 = QFrame(self.frame_5)
        self.frame1.setObjectName(u"frame1")
        self.gridLayout_2 = QGridLayout(self.frame1)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_7 = QFrame(self.frame1)
        self.frame_7.setObjectName(u"frame_7")
        sizePolicy3.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy3)
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.frame_7)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalScrollBar = QScrollBar(self.frame_7)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setInvertedControls(True)

        self.gridLayout_8.addWidget(self.horizontalScrollBar, 0, 0, 1, 1)

        self.label_3 = QLabel(self.frame_7)
        self.label_3.setObjectName(u"label_3")
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.label_3.setMinimumSize(QSize(100, 0))

        self.gridLayout_8.addWidget(self.label_3, 0, 1, 1, 1)


        self.gridLayout_2.addWidget(self.frame_7, 3, 0, 1, 2)

        self.widget_3 = PlotWidget(self.frame1)
        self.widget_3.setObjectName(u"widget_3")

        self.gridLayout_2.addWidget(self.widget_3, 2, 1, 1, 1)

        self.widget_2 = PlotWidget(self.frame1)
        self.widget_2.setObjectName(u"widget_2")

        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 1)

        self.widget = QFrame(self.frame1)
        self.widget.setObjectName(u"widget")
        self.widget.setFrameShape(QFrame.StyledPanel)
        self.widget.setFrameShadow(QFrame.Raised)

        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 2)

        self.label_5 = QLabel(self.frame1)
        self.label_5.setObjectName(u"label_5")
        sizePolicy3.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy3)
        self.label_5.setMinimumSize(QSize(0, 37))
        self.label_5.setBaseSize(QSize(0, 58))

        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)

        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)

        self.gridLayout_13.addWidget(self.frame1, 0, 0, 1, 1)

        self.gridLayout_13.setRowStretch(0, 3)

        self.gridLayout.addWidget(self.frame_5, 0, 1, 2, 1)

        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(3, 1)

        self.verticalLayout_2.addWidget(self.frame_2)

        self.verticalLayout_2.setStretch(0, 2)

        self.horizontalLayout_3.addWidget(self.frame_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 954, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExport = QMenu(self.menubar)
        self.menuExport.setObjectName(u"menuExport")
        self.menuPump_Probe = QMenu(self.menubar)
        self.menuPump_Probe.setObjectName(u"menuPump_Probe")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuBin_Data = QMenu(self.menuTools)
        self.menuBin_Data.setObjectName(u"menuBin_Data")
        self.menuRemove_outliers = QMenu(self.menuTools)
        self.menuRemove_outliers.setObjectName(u"menuRemove_outliers")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuImage_mode = QMenu(self.menuView)
        self.menuImage_mode.setObjectName(u"menuImage_mode")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuPump_Probe.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionOpen_ZIP)
        self.menuFile.addAction(self.actionOpen_NPY)
        self.menuFile.addAction(self.actionImport_Dataset)
        self.menuFile.addAction(self.actionOpen_single_H5_serie)
        self.menuFile.addAction(self.actionOpen_SPE)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDummy_data)
        self.menuFile.addAction(self.actionImport_Dataset_ON_OFF)
        self.menuExport.addAction(self.actionImage)
        self.menuExport.addAction(self.actionArray)
        self.menuExport.addAction(self.actionDataset)
        self.menuExport.addAction(self.actionDataset_ON_OFF)
        self.menuPump_Probe.addAction(self.actionGroup_by_delay)
        self.menuPump_Probe.addAction(self.actionROI_avg_intensity)
        self.menuPump_Probe.addAction(self.actionSubtract_first_image)
        self.menuPump_Probe.addAction(self.actionSelect_loops)
        self.menuPump_Probe.addAction(self.actionDiff_On_Off)
        self.menuPump_Probe.addAction(self.actionSwap_On_Off)
        self.menuPump_Probe.addAction(self.actionShow_On_Off)
        self.menuPump_Probe.addAction(self.actionShow_On)
        self.menuPump_Probe.addAction(self.actionShow_Off)
        self.menuPump_Probe.addAction(self.actionGaussian_smooth)
        self.menuPump_Probe.addAction(self.actionGaussian_smooth_ON_OFF)
        self.menuPump_Probe.addAction(self.actionON_OFF)
        self.menuPump_Probe.addAction(self.actionRemove_hot_n_2)
        self.menuTools.addAction(self.actionRadial_Average)
        self.menuTools.addAction(self.menuBin_Data.menuAction())
        self.menuTools.addAction(self.actionSlice_Data)
        self.menuTools.addAction(self.actionDownsample_to_16bit)
        self.menuTools.addAction(self.actionSet_000_position)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPattern_simulator)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPlotter)
        self.menuTools.addAction(self.actionConsole)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalibrate_image)
        self.menuTools.addAction(self.actionMeasure_distance)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuRemove_outliers.menuAction())
        self.menuBin_Data.addAction(self.action2x2)
        self.menuBin_Data.addAction(self.action3x3)
        self.menuBin_Data.addAction(self.action5x5)
        self.menuBin_Data.addAction(self.action10x10)
        self.menuRemove_outliers.addAction(self.action1)
        self.menuRemove_outliers.addAction(self.action2)
        self.menuRemove_outliers.addAction(self.action3)
        self.menuRemove_outliers.addAction(self.action4)
        self.menuRemove_outliers.addAction(self.action5)
        self.menuView.addAction(self.actionMetadata_Panel)
        self.menuView.addAction(self.menuImage_mode.menuAction())
        self.menuImage_mode.addAction(self.actionLinear)
        self.menuImage_mode.addAction(self.actionLog)
        self.menuImage_mode.addAction(self.actionArcsinh)
        self.menuImage_mode.addAction(self.actionSquare)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"UED dataset explorer", None))
        self.actionOpen_TIFFs.setText(QCoreApplication.translate("MainWindow", u"Open TIFFs", None))
        self.actionOpen_Zip_TIFFs.setText(QCoreApplication.translate("MainWindow", u"Open Zip TIFFs", None))
        self.actionOpen_Zip_H5.setText(QCoreApplication.translate("MainWindow", u"Open Zip H5", None))
        self.actionProject_TRee.setText(QCoreApplication.translate("MainWindow", u"Project Tree", None))
        self.actiontest_bar.setText(QCoreApplication.translate("MainWindow", u"test bar", None))
        self.actionOpen_Folder.setText(QCoreApplication.translate("MainWindow", u"Open Folder", None))
        self.actionOpen_ZIP.setText(QCoreApplication.translate("MainWindow", u"Open ZIP", None))
        self.actionImage.setText(QCoreApplication.translate("MainWindow", u"Image to NPY", None))
        self.actionArray.setText(QCoreApplication.translate("MainWindow", u"Array to NPY", None))
        self.actionDataset.setText(QCoreApplication.translate("MainWindow", u"Dataset", None))
        self.actionOpen_NPY.setText(QCoreApplication.translate("MainWindow", u"Open NPY", None))
        self.actionGroup_by_delay.setText(QCoreApplication.translate("MainWindow", u"Group by delay", None))
        self.actionROI_avg_intensity.setText(QCoreApplication.translate("MainWindow", u"ROI avg intensity", None))
        self.actionImport_Dataset.setText(QCoreApplication.translate("MainWindow", u"Import Dataset", None))
        self.actionSet_center.setText(QCoreApplication.translate("MainWindow", u"Set center", None))
        self.actionCalculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.actionSubtract_first_image.setText(QCoreApplication.translate("MainWindow", u"Subtract first image", None))
        self.actionRadial_Average.setText(QCoreApplication.translate("MainWindow", u"Radial Average", None))
        self.action2x2.setText(QCoreApplication.translate("MainWindow", u"2x2", None))
        self.action3x3.setText(QCoreApplication.translate("MainWindow", u"3x3", None))
        self.action5x5.setText(QCoreApplication.translate("MainWindow", u"5x5", None))
        self.action10x10.setText(QCoreApplication.translate("MainWindow", u"10x10", None))
        self.actionSlice_Data.setText(QCoreApplication.translate("MainWindow", u"Slice Data", None))
        self.actionDownsample_to_16bit.setText(QCoreApplication.translate("MainWindow", u"Downsample to 16bit", None))
        self.actionOpen_single_H5_serie.setText(QCoreApplication.translate("MainWindow", u"Open single H5 serie", None))
        self.actionSet_000_position.setText(QCoreApplication.translate("MainWindow", u"Set 000 position", None))
        self.actionPattern_simulator.setText(QCoreApplication.translate("MainWindow", u"Pattern simulator", None))
        self.actionOpen_SPE.setText(QCoreApplication.translate("MainWindow", u"Open SPE", None))
        self.actionPlotter.setText(QCoreApplication.translate("MainWindow", u"Plotter", None))
        self.actionCalibrate_image.setText(QCoreApplication.translate("MainWindow", u"Calibrate image", None))
        self.actionMeasure_distance.setText(QCoreApplication.translate("MainWindow", u"Measure distance", None))
        self.actionNew_window.setText(QCoreApplication.translate("MainWindow", u"New window", None))
        self.actionAdd_ROI.setText(QCoreApplication.translate("MainWindow", u"Add ROI", None))
        self.actionRemove_ROI.setText(QCoreApplication.translate("MainWindow", u"Remove ROI", None))
        self.actionRemove_All.setText(QCoreApplication.translate("MainWindow", u"Remove All", None))
        self.actionSelect_loops.setText(QCoreApplication.translate("MainWindow", u"Select loops", None))
        self.actionConsole.setText(QCoreApplication.translate("MainWindow", u"Console", None))
        self.actionMetadata_Panel.setText(QCoreApplication.translate("MainWindow", u"Metadata Panel", None))
        self.actionLinear.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.actionLog.setText(QCoreApplication.translate("MainWindow", u"Log", None))
        self.actionArcsinh.setText(QCoreApplication.translate("MainWindow", u"Arcsinh", None))
        self.actionSquare.setText(QCoreApplication.translate("MainWindow", u"Square", None))
        self.actionNew_window_2.setText(QCoreApplication.translate("MainWindow", u"New window", None))
        self.actionDiff_On_Off.setText(QCoreApplication.translate("MainWindow", u"Diff On-Off", None))
        self.actionSwap_On_Off.setText(QCoreApplication.translate("MainWindow", u"Swap On-Off", None))
        self.actionDummy_data.setText(QCoreApplication.translate("MainWindow", u"Dummy data", None))
        self.actionShow_On_Off.setText(QCoreApplication.translate("MainWindow", u"Show On/Off", None))
        self.actionShow_On.setText(QCoreApplication.translate("MainWindow", u"Show On", None))
        self.actionShow_Off.setText(QCoreApplication.translate("MainWindow", u"Show Off", None))
        self.actionGaussian_smooth.setText(QCoreApplication.translate("MainWindow", u"Gaussian smooth", None))
        self.actionDataset_ON_OFF.setText(QCoreApplication.translate("MainWindow", u"Dataset ON OFF", None))
        self.actionImport_Dataset_ON_OFF.setText(QCoreApplication.translate("MainWindow", u"Import Dataset ON OFF", None))
        self.actionGaussian_smooth_ON_OFF.setText(QCoreApplication.translate("MainWindow", u"Gaussian smooth ON OFF", None))
        self.actionON_OFF.setText(QCoreApplication.translate("MainWindow", u"ON-OFF", None))
        self.actionRemove_hot_n_2.setText(QCoreApplication.translate("MainWindow", u"Remove hot (n=2)", None))
        self.actionRemove_outliers.setText(QCoreApplication.translate("MainWindow", u"Remove outliers imgON", None))
        self.actionRemove_outliers_imgOFF.setText(QCoreApplication.translate("MainWindow", u"Remove outliers imgOFF", None))
        self.action1.setText(QCoreApplication.translate("MainWindow", u"1 SD", None))
        self.action2.setText(QCoreApplication.translate("MainWindow", u"2 SD", None))
        self.action3.setText(QCoreApplication.translate("MainWindow", u"2.5 SD", None))
        self.action4.setText(QCoreApplication.translate("MainWindow", u"3 SD", None))
        self.action5.setText(QCoreApplication.translate("MainWindow", u"4 SD", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Fit tools", None))
        self.fit_G.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.fit_V.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.fit_voigt_btn.setText(QCoreApplication.translate("MainWindow", u"Fit all Voigt", None))
        self.fit_gauss_btn.setText(QCoreApplication.translate("MainWindow", u"Fit all Gauss", None))
        self.fit_chkbx.setText(QCoreApplication.translate("MainWindow", u"Fit", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"ROI tools", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Remove All", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"ROI autoscale", None))
        self.label_2.setText("")
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Track evolution", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Snap", None))
        self.roi_chkbx.setText(QCoreApplication.translate("MainWindow", u"ROI", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Ruler", None))
        self.label.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Image tools", None))
        self.doubleSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.checkBox_pump.setText(QCoreApplication.translate("MainWindow", u"Check pump ", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Rotate", None))
        self.sum_chkbx.setText(QCoreApplication.translate("MainWindow", u"Sum All", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Rainbow", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Grayscale", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"Hot-Cold", None))

        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Sum range:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Colormap:", None))
        self.export_img_btn.setText(QCoreApplication.translate("MainWindow", u"Img to Clipboard", None))
        self.label_7.setText("")
        self.shift_0order_btn.setText(QCoreApplication.translate("MainWindow", u"shift 0th order", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"y", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"PT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Info", None))
        self.notes_lbl.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Notes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Fit", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menuPump_Probe.setTitle(QCoreApplication.translate("MainWindow", u"Pump-Probe", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuBin_Data.setTitle(QCoreApplication.translate("MainWindow", u"Bin Data", None))
        self.menuRemove_outliers.setTitle(QCoreApplication.translate("MainWindow", u"Remove outliers", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuImage_mode.setTitle(QCoreApplication.translate("MainWindow", u"Image mode", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

